### ISSUE TITLE
Linux Mint Debian Edition + Spotify repo + Yggdrasil =

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/yggdrasil-package-debian#1]
>The repository may no longer be available or could not be contacted because of network problems. If available an older version of the failed index will be used. Otherwise the repository will be ignored. Check your network connection and ensure the repository address in the preferences is correct.
>GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D1742AD60D811D58The repository 'http://repository.spotify.com stable InRelease' is not signed.

**Comment by neilalexander** [comment]
We are not anything to do with `repository.spotify.com`?

**Comment by styromaniac** [comment]
It interferes with the repo being reached, so yes, you have something to do with it. Give it a try.

On Android, Ygg also interferes with a few apps.

**Comment by neilalexander** [comment]
The error that you pasted is a GPG error, probably you have not imported the GPG key for `repository.spotify.com`. That’s neither an Yggdrasil nor a network problem. You may want to check your apt keyring.

**Comment by styromaniac** [comment]
>Try telling aptitude to not use IPv6, or better yet, edit /etc/gai.conf to give a custom precedence for 0200::/7 or similar.

Why did you delete this comment?

Do you mean to put in the Ygg IPv6 address?

**Comment by neilalexander** [comment]
Because I re-read the error you pasted and my previous edit is irrelevant to a GPG error. A GPG error is a problem with keys, not the network.

**Comment by styromaniac** [comment]
Well, it seems that every time I install Ygg that the network connectivity decays somehow and grinds to a halt. I hope that you eventually realize that there are problems on both Linux and Android specifically with Ygg and nothing else.

You should continue to help as you've attempted earlier, before the deletion.

**Comment by neilalexander** [comment]
I am going to guess that you don't have IPv6 internet connectivity normally, and that running Yggdrasil is tricking your operating system into trying IPv6 connectivity for internet destinations, but that's ultimately a separate issue and has been discussed at length at yggdrasil-network/yggdrasil-go#437 and yggdrasil-network/yggdrasil-go#180. Let's continue to discuss in one of those issues instead.

The same thing would likely happen with any other VPN software that carries IPv6 prefixes, for what it's worth, and I suspect Android is affected similarly to how Linux is. This is not something we can easily fix, because we can't arbitrarily control the prefix precedence of the host operating system.

**Comment by styromaniac** [comment]
> I am going to guess that you don't have IPv6 internet connectivity normally, and that running Yggdrasil is tricking your operating system into trying IPv6 connectivity for internet destinations, but that's ultimately a separate issue and has been discussed at length at [yggdrasil-network/yggdrasil-go#437](https://github.com/yggdrasil-network/yggdrasil-go/issues/437) and [yggdrasil-network/yggdrasil-go#180](https://github.com/yggdrasil-network/yggdrasil-go/issues/180). Let's continue to discuss in one of those issues instead.
> 
> The same thing would likely happen with any other VPN software that carries IPv6 prefixes, for what it's worth, and I suspect Android is affected similarly to how Linux is. This is not something we can easily fix, because we can't arbitrarily control the prefix precedence of the host operating system.

You've guessed correctly. I'm glad that you're onto something here.
